<a href="https://colab.research.google.com/github/h1mmeister/Artificial_Neural_Network/blob/main/Artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [75]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [76]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [77]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1]
y = dataset.iloc[:, -1]

In [78]:
X.shape

(10000, 10)

In [79]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [80]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
dtypes: float64(2), int64(6), object(2)
memory usage: 781.4+ KB


In [81]:
X.describe()

CreditScore           Age  ...  IsActiveMember  EstimatedSalary
count  10000.000000  10000.000000  ...    10000.000000     10000.000000
mean     650.528800     38.921800  ...        0.515100    100090.239881
std       96.653299     10.487806  ...        0.499797     57510.492818
min      350.000000     18.000000  ...        0.000000        11.580000
25%      584.000000     32.000000  ...        0.000000     51002.110000
50%      652.000000     37.000000  ...        1.000000    100193.915000
75%      718.000000     44.000000  ...        1.000000    149388.247500
max      850.000000     92.000000  ...        1.000000    199992.480000

[8 rows x 8 columns]

In [82]:
X = X.values
y = y.values

In [83]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [84]:
type(X), type(y)

(numpy.ndarray, numpy.ndarray)

### Encoding categorical data

Label Encoding the "Gender" column

In [85]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [86]:
print(X)


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [87]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(),[1])], remainder = "passthrough")
X = ct.fit_transform(X)

In [88]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

### Feature Scaling

In [90]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [91]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [92]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the second hidden layer

In [93]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the output layer

In [94]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

## Part 3 - Training the ANN

### Compiling the ANN

In [95]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

### Training the ANN on the Training set

In [96]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6184 - accuracy: 0.7023
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4793 - accuracy: 0.7982
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4471 - accuracy: 0.8053
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4246 - accuracy: 0.8230
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4200 - accuracy: 0.8202
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4025 - accuracy: 0.8279
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3962 - accuracy: 0.8302
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3831 - accuracy: 0.8366
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3990 - accuracy: 0.8357
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3945 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [97]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [98]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


### Making the Confusion Matrix

In [99]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1537   70]
 [ 213  180]]


0.8585